package com.seektop.fund.enums;

import com.seektop.common.local.base.parse.LocalCommonConfig;
import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum FundLanguageMvcEnum implements LocalCommonConfig {


    RECHARGE_PAYMENT_MECHANT_NOT_EXIST("RECHARGE_PAYMENT_MERCHANT_NOT_EXIST","商户不存在"),
    RECHARGE_PAYMENT_HANDLER_ERROR("RECHARGE_PAYMENT_HANDLER_ERROR","充值通道异常(2),请联系客服."),

    //充值
    RECHARGE_ORDER_EMPTY("RECHARGE_ORDER_EMPTY","充值订单为空"),
    RECHARGE_ORDER_NOT_EXIST("RECHARGE_ORDER_NOT_EXIST","充值订单不存在"),
    RECHARGE_ORDER_STATUS_ERROR("RECHARGE_ORDER_STATUS_ERROR","充值订单异常，请联系客服"),
    RECHARGE_ORDER_CONFIRM_ERROR("RECHARGE_ORDER_CONFIRM_STATUS_ERROR","充值订单确认异常，请联系客服"),
    RECHARGE_ORDER_EXPIRED_OR_NOT_EXIST("RECHARGE_ORDER_EXPIRED_OR_NOT_EXIST","充值订单过期或不存在"),
    RECHARGE_ORDER_AMOUNT_MIN_LIMIT("RECHARGE_ORDER_AMOUNT_MIN_LIMIT","单笔最小充值金额为元"),
    RECHARGE_ORDER_REQ_SUCCESS("RECHARGE_ORDER_REQ_SUCCESS","补单申请成功"),
    RECHARGE_ORDER_GET_PAYNAME_LIST_ERROR("RECHARGE_ORDER_GET_PAYNAME_LIST_ERROR","获取充值付款人姓名监控列表发生错误"),
    RECHARGE_ORDER_GET_PAYNAME_SUM_ERROR("RECHARGE_ORDER_GET_PAYNAME_SUM_ERROR","获取充值付款人姓名监控总数发生错误"),
    RECHARGE_ORDER_GET_PAYNAME_COUNT_ERROR("RECHARGE_ORDER_GET_PAYNAME_COUNT_ERROR","获取充值付款人姓名监控次数发生错误"),
    RECHARGE_ORDER_SAVE_PAYNAME_COUNT_ERROR("RECHARGE_ORDER_SAVE_PAYNAME_COUNT_ERROR","保存充值付款人姓名监控次数发生错误"),
    RECHARGE_ORDER_ERROR("RECHARGE_ORDER_ERROR","订单号异常"),
    RECHARGE_MERCHANT_OFF("RECHARGE_MERCHANT_OFF","充值渠道不存在或已关闭"),
    RECHARGE_MERCHANT_NOT_EXIST("RECHARGE_MERCHANT_OFF","充值渠道配置不存在"),
    RECHARGE_MERCHANT_HANDLER_EXIST("RECHARGE_MERCHANT_HANDLER_EXIST","获取handler异常"),


    //代客充值
    RECHARGE_AGENT_ORDER_NOT_EXIST("RECHARGE_AGENT_ORDER_NOT_EXIST","代客充值订单不存在"),
    RECHARGE_AGENT_ORDER_SUBMITED("RECHARGE_AGENT_ORDER_SUBMITED","代客充值订单已提交,请勿重复刷新"),
    RECHARGE_CREATE_ORDER_ERROR("RECHARGE_CREATE_ORDER_ERROR","订单创建失败"),

    //提现
    WITHDRAW_ORDER_EMPTY("WITHDRAW_ORDER_EMPTY","提现订单为空"),
    WITHDRAW_ORDER_NOT_EXIST("WITHDRAW_ORDER_NOT_EXIST","提现订单不存在"),
    WITHDRAW_ORDER_STATUS_ERROR("RECHARGE_ORDER_STATUS_ERROR","提现订单状态错误，请联系客服"),
    WITHDRAW_ORDER_CONFIRM_ERROR("RECHARGE_ORDER_CONFIRM_STATUS_ERROR","充值订单确认异常，请联系客服"),
    WITHDRAW_NORMAL_CONFIG_SAVE_ERROR("WITHDRAW_NORMAL_CONFIG_SAVE_ERROR","保存普通提现配置发生错误"),
    WITHDRAW_NORMAL_CONFIG_EMPTY("WITHDRAW_NORMAL_CONFIG_EMPTY","普通提现配置未设置"),
    WITHDRAW_NORMAL_CONFIG_GET_ERROR("WITHDRAW_NORMAL_CONFIG_GET_ERROR","查询普通提现配置发生错误"),
    WITHDRAW_LARGE_CONFIG_SAVE_ERROR("WITHDRAW_LARGE_CONFIG_SAVE_ERROR","保存大额提现配置发生错误"),
    WITHDRAW_LARGE_CONFIG_GET_ERROR("WITHDRAW_LARGE_CONFIG_GET_ERROR","查询大额提现配置发生错误"),
    WITHDRAW_LARGE_CONFIG_EMPTY("WITHDRAW_LARGE_CONFIG_EMPTY","大额提现配置未设置"),
    WITHDRAW_PROXY_CONFIG_SAVE_ERROR("WITHDRAW_PROXY_CONFIG_SAVE_ERROR","保存代理提现配置发生错误"),
    WITHDRAW_PROXY_CONFIG_GET_ERROR("WITHDRAW_PROXY_CONFIG_GET_ERROR","查询代理提现配置发生错误"),
    WITHDRAW_PROXY_CONFIG_EMPTY("WITHDRAW_PROXY_CONFIG_EMPTY","代理提现配置未设置"),
    WITHDRAW_COMMON_CONFIG_SAVE_ERROR("WITHDRAW_COMMON_CONFIG_SAVE_ERROR","保存通用提现配置发生错误"),
    WITHDRAW_COMMON_CONFIG_GET_ERROR("WITHDRAW_COMMON_CONFIG_GET_ERROR","查询通用提现配置发生错误"),
    WITHDRAW_COMMON_CONFIG_EMPTY("WITHDRAW_COMMON_CONFIG_EMPTY","通用提现配置未设置"),

    //通用
    LOGIN_INVALID("LOGIN_INVALID","登录失效"),
    FREQUENT_OPERATIONS("FREQUENT_OPERATIONS","操作过于频繁，建议您稍后再试"),
    OPERATE_ERROR_CONTACT_CUSTOMER_SERVICE("OPERATE_ERROR_CONTACT_CUSTOMER_SERVICE","暂不能进行此操作，请联系客服确认账号状态"),
    AMOUNT_LIMIT_ZERO("AMOUNT_LIMIT_ZERO","操作金额不能小于等于0"),
    PARAM_TYPE_ERROR("PARAM_TYPE_ERROR","操作类型参数错误"),
    TARGET_USER_NOT_EXIST("TARGET_USER_NOT_EXIST","目标用户不存在"),
    TARGET_USER_NOT_DIRECT_SUB("TARGET_USER_NOT_DIRECT_SUB","目标用户不是直属下级"),
    FUND_PASSWORD_NOT_SET("FUND_PASSWORD_NOT_SET","您尚未设置资金密码"),
    FUND_PASSWORD_ERROR("FUND_PASSWORD_NOT_SET","资金密码错误"),
    SERVICE_IS_BUSY("SERVICE_IS_BUSY","服务忙,请稍后再试!"),
    ADMIN_NOT_EXIST("ADMIN_NOT_EXIST","管理员不存在"),

    INVALID_PARAM("INVALID_PARAM","参数错误"),
    SETTING_NOT_EXIST("SETTING_NOT_EXIST","保存失败，配置不存在"),
    SETTING_SAVE_ERROR("SETTING_SAVE_ERROR","保存配置时发生错误"),
    SETTING_GET_ERROR("SETTING_GET_ERROR","获取配置时发生错误"),
    DOWNLOADING_MAX_20W("DOWNLOADING_MAX_20W","正在下载，请在下载列表查看(一次最多导出20W数据)"),
    DOWNLOAD_TIME_LIMIT_FIVE_MINUTE("DOWNLOAD_TIME_LIMIT_FIVE_MINUTE","5分钟只能导出一次"),
    DOWNLOADING_CHECK_ON_DOWNLOAD_LIST("DOWNLOADING_CHECK_ON_DOWNLOAD_LIST","正在下载，请在下载列表查看"),

    //用户
    USET_GET_WHITE_LIST_ERROR("USET_GET_WHITE_LIST_ERROR","获取用户账号白名单列表发生错误"),
    USET_WHITE_MAX_100("USET_WHITE_MAX_100","每次最多只能添加100个姓名白名单"),
    USET_PAYERNAME_GET_WHITE_LIST_ERROR("USET_PAYERNAME_GET_WHITE_LIST_ERROR","获取付款人姓名白名单列表发生错误"),
    USET_PAYERNAME_CREATE_ERROR("USET_PAYERNAME_CREATE_ERROR","创建付款人姓名白名单发生错误"),
    USET_PAYERNAME_ID_NOT_EMPTY("USET_PAYERNAME_ID_EMPTY","付款人姓名白名单记录ID不能为空"),
    USET_PAYERNAME_ID_NOT_EXIST("USET_PAYERNAME_ID_NOT_EXIST","付款人姓名白名单记录ID不存在"),
    USET_PAYERNAME_DELETE_WHITE_ERROR("USET_PAYERNAME_DELETE_WHITE_ERROR","删除付款人姓名白名单发生错误"),
    USER_NOT_EXIST("USER_NOT_EXIST","用户不存在"),
    USER_NAME_NOT_EMPTY("USER_NAME_NOT_EMPTY","用户名不能为空"),
    USER_ACCOUNT_NOT_EXIST("USER_ACCOUNT_NOT_EXIST","用户账号不存在"),
    USER_ACCOUNT_ALREADY_IN_WHITE_LIST("USER_ACCOUNT_ALREADY_IN_WHITE_LIST","用户账号已经在白名单"),
    USER_ACCOUNT_CREATE_WHITE_ERROR("USER_ACCOUNT_CREATE_WHITE_ERROR","创建用户账号白名单发生错误"),
    USER_ACCOUNT_WHITE_NOT_EXIST("USER_ACCOUNT_WHITE_NOT_EXIST","用户账号白名单记录不存在"),
    USER_ACCOUNT_WHITE_DELETE_ERROR("USER_ACCOUNT_WHITE_DELETE_ERROR","删除用户账号白名单发生错误"),
    USER_ID_EMPTY("USER_ID_EMPTY","用户ID不能为空"),


    BANK_BIND_LIST_GET_ERROR("BANK_BIND_LIST_GET_ERROR","银行卡绑定列表查询失败!"),
    USDT_BIND_LIST_GET_ERROR("USDT_BIND_LIST_GET_ERROR","USDT 绑定列表查询失败!"),

    //用户层级
    FUND_LEVEL_ID_NOT_EXIST("FUND_LEVEL_ID_NOT_EXIST","被调整层级ID不存在"),
    FUND_LEVEL_TARGER_ID_NOT_EXIST("FUND_LEVEL_ID_NOT_EXIST","目标层级ID不存在"),

    //用户流水
    USER_EFFECT_SUBMIT("USER_EFFECT_SUBMIT","提交成功，待审核"),

    //C2C
    C2C_EGG_ID_NOT_EXIST("C2C_EGG_ID_NOT_EXIST","彩蛋记录ID不存在，无法停止"),
    C2C_EGG_NOT_RUNNING("C2C_EGG_NOT_RUNNING","彩蛋活动不在运行中，无法停止"),
    C2C_EGG_IS_RUNNING("C2C_EGG_IS_RUNNING","已经存在进行中的彩蛋活动，无法重复开启"),
    C2C_EGG_GET_INFO_ERROR("C2C_EGG_GET_INFO_ERROR","从活动服务获取彩蛋配置发生错误:返回的RPC结果是空"),
    C2C_EGG_GET_INFO_STATUS_ERROR("C2C_EGG_GET_INFO_STATUS_ERROR","从活动服务获取彩蛋配置发生错误:返回RPC状态不正确"),
    C2C_EGG_GET_INFO_EMPTY("C2C_EGG_GET_INFO_EMPTY","从活动服务获取彩蛋配置发生错误:返回的配置是空"),

    //USDT
    WALLET_NICKNAME_TOO_LONG("WALLET_NICKNAME_TOO_LONG","钱包别名长度超限,请重新输入"),
    WALLET_COIN_NOT_EXIST("WALLET_NICKNAME_TOO_LONG","币种不存在,核对后重新输入"),
    WALLET_PROTOCOL_NOT_EXIST("WALLET_PROTOCOL_NOT_EXIST","协议不存在,核对后重新输入"),
    WALLET_ADDRESS_FORMAT_ERROR("WALLET_ADDRESS_FORMAT_ERROR","地址格式错误,核对后重新输入"),
    WALLET_ADDRESS_EXIST("WALLET_ADDRESS_EXIST","地址已存在"),
    WALLET_ADDRESSES_MAX_FIVE("WALLET_ADDRESSES_MAX_FIVE","地址最多添加5个"),

    //代理
    PROXY_INFO_NOT_ACQUIRED("PROXY_INFO_NOT_ACQUIRED","无法获取代理信息，请稍后重试"),

    BANKCARD_WITHDRAW_ID_NOT_EXIST("BANKCARD_WITHDRAW_ID_NOT_EXIST","提现银行卡ID不存在"),
    BANKCARD_RECHARGE_ID_NOT_EXIST("BANKCARD_RECHARGE_ID_NOT_EXIST","充值银行卡ID不存在"),

    ;

    private String key;

    private String desc;

    @Override
    public String getModule() {
        return "fund-mvc";
    }

}
